apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: curielogger
  namespace: {{ .Release.Namespace }}
  labels:
    app: curielogger
    app.kubernetes.io/part-of: "curiefense"
spec:
  host: curielogger.{{ .Release.Namespace }}.svc.cluster.local
  trafficPolicy:
    tls:
      mode: DISABLE
