apiVersion: v1
kind: Namespace
metadata:
  name: echoserver
  labels:
    istio-injection: enabled
    app.kubernetes.io/part-of: "curiefense"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoserver
  namespace: echoserver
  labels:
    app.kubernetes.io/part-of: "curiefense"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echoserver
  template:
    metadata:
      labels:
        app: echoserver
        app.kubernetes.io/part-of: "curiefense"
    spec:
      containers:
      - image: gcr.io/google_containers/echoserver:1.0
        imagePullPolicy: IfNotPresent
        name: echoserver
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: echoserver
  namespace: echoserver
  labels:
    app: echoserver
    service: echoserver
    app.kubernetes.io/part-of: "curiefense"
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: echoserver
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: echoserver-gateway
  namespace: echoserver
  labels:
    app.kubernetes.io/part-of: "curiefense"
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: echoserver
  namespace: echoserver
  labels:
    app.kubernetes.io/part-of: "curiefense"
spec:
  hosts:
  - "*"
  gateways:
  - echoserver-gateway
  http:
  - match:
     - uri:
        prefix: "/productpage"
    route:
    - destination:
        host: echoserver
        port:
          number: 8080
