---
apiVersion: v1
kind: Secret
data:
  sshkey: "LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0KYjNCbGJuTnphQzFyWlhrdGRqRUFBQUFBQkc1dmJtVUFBQUFFYm05dVpRQUFBQUFBQUFBQkFBQUFNd0FBQUF0emMyZ3RaVwpReU5UVXhPUUFBQUNDWk8vdTJHN1RtaENMWnBkZDVYQXQ3VTdPczluYlpxTjZPQWZKVStQc0FrQUFBQUtDWWNFQ3ltSEJBCnNnQUFBQXR6YzJndFpXUXlOVFV4T1FBQUFDQ1pPL3UyRzdUbWhDTFpwZGQ1WEF0N1U3T3M5bmJacU42T0FmSlUrUHNBa0EKQUFBRUFwNThPZEFZTUZaTFNiTjQ4bzNMbWgvbFRGa0UwYk51SmhtRWhWYkFOak1wazcrN1lidE9hRUl0bWwxM2xjQzN0VApzNnoyZHRtbzNvNEI4bFQ0K3dDUUFBQUFHbVJsYlc4Z2MzTm9hMlY1SUdadmNpQmpiMjVtYzJWeWRtVnlBUUlECi0tLS0tRU5EIE9QRU5TU0ggUFJJVkFURSBLRVktLS0tLQo="
metadata:
  labels:
    app.kubernetes.io/name: sshkey
  name: sshkey
  namespace: curiefense
type: Opaque
